// Mapa completo de DDI (código de discagem direta internacional) → país(es)
// Baseado no padrão ITU-T E.164

export interface DdiCountry {
  /** Nome do país em português */
  name: string
  /** Código ISO 3166-1 alpha-2 (para gerar emoji de bandeira) */
  iso: string
}

/** Gera emoji de bandeira a partir de um código ISO 3166-1 alpha-2 */
export function flagEmoji(iso: string): string {
  return [...iso.toUpperCase()]
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('')
}

/**
 * Mapa de DDI → lista de países associados.
 * Alguns códigos (ex: 1, 7) cobrem múltiplos países.
 */
export const DDI_MAP: Record<number, DdiCountry[]> = {
  1: [
    { name: 'Estados Unidos', iso: 'US' },
    { name: 'Canadá', iso: 'CA' },
    { name: 'Porto Rico', iso: 'PR' },
    { name: 'Jamaica', iso: 'JM' },
    { name: 'Trinidad e Tobago', iso: 'TT' },
    { name: 'Bahamas', iso: 'BS' },
    { name: 'Barbados', iso: 'BB' },
    { name: 'Dominica', iso: 'DM' },
    { name: 'Granada', iso: 'GD' },
    { name: 'Ilhas Virgens (EUA)', iso: 'VI' },
    { name: 'Ilhas Virgens (Reino Unido)', iso: 'VG' },
    { name: 'Anguilla', iso: 'AI' },
    { name: 'Antígua e Barbuda', iso: 'AG' },
    { name: 'Ilhas Cayman', iso: 'KY' },
    { name: 'Ilhas Turks e Caicos', iso: 'TC' },
    { name: 'Montserrat', iso: 'MS' },
    { name: 'São Cristóvão e Névis', iso: 'KN' },
    { name: 'Santa Lúcia', iso: 'LC' },
    { name: 'São Vicente e Granadinas', iso: 'VC' },
    { name: 'Sint Maarten', iso: 'SX' },
  ],
  7: [
    { name: 'Rússia', iso: 'RU' },
    { name: 'Cazaquistão', iso: 'KZ' },
  ],
  20: [{ name: 'Egito', iso: 'EG' }],
  27: [{ name: 'África do Sul', iso: 'ZA' }],
  30: [{ name: 'Grécia', iso: 'GR' }],
  31: [{ name: 'Países Baixos', iso: 'NL' }],
  32: [{ name: 'Bélgica', iso: 'BE' }],
  33: [{ name: 'França', iso: 'FR' }],
  34: [{ name: 'Espanha', iso: 'ES' }],
  36: [{ name: 'Hungria', iso: 'HU' }],
  39: [{ name: 'Itália', iso: 'IT' }],
  40: [{ name: 'Romênia', iso: 'RO' }],
  41: [{ name: 'Suíça', iso: 'CH' }],
  43: [{ name: 'Áustria', iso: 'AT' }],
  44: [{ name: 'Reino Unido', iso: 'GB' }],
  45: [{ name: 'Dinamarca', iso: 'DK' }],
  46: [{ name: 'Suécia', iso: 'SE' }],
  47: [
    { name: 'Noruega', iso: 'NO' },
    { name: 'Svalbard e Jan Mayen', iso: 'SJ' },
  ],
  48: [{ name: 'Polônia', iso: 'PL' }],
  49: [{ name: 'Alemanha', iso: 'DE' }],
  51: [{ name: 'Peru', iso: 'PE' }],
  52: [{ name: 'México', iso: 'MX' }],
  53: [{ name: 'Cuba', iso: 'CU' }],
  54: [{ name: 'Argentina', iso: 'AR' }],
  55: [{ name: 'Brasil', iso: 'BR' }],
  56: [{ name: 'Chile', iso: 'CL' }],
  57: [{ name: 'Colômbia', iso: 'CO' }],
  58: [{ name: 'Venezuela', iso: 'VE' }],
  60: [{ name: 'Malásia', iso: 'MY' }],
  61: [
    { name: 'Austrália', iso: 'AU' },
    { name: 'Ilhas Cocos', iso: 'CC' },
    { name: 'Ilha Christmas', iso: 'CX' },
  ],
  62: [{ name: 'Indonésia', iso: 'ID' }],
  63: [{ name: 'Filipinas', iso: 'PH' }],
  64: [{ name: 'Nova Zelândia', iso: 'NZ' }],
  65: [{ name: 'Singapura', iso: 'SG' }],
  66: [{ name: 'Tailândia', iso: 'TH' }],
  81: [{ name: 'Japão', iso: 'JP' }],
  82: [{ name: 'Coreia do Sul', iso: 'KR' }],
  84: [{ name: 'Vietnã', iso: 'VN' }],
  86: [{ name: 'China', iso: 'CN' }],
  90: [{ name: 'Turquia', iso: 'TR' }],
  91: [{ name: 'Índia', iso: 'IN' }],
  92: [{ name: 'Paquistão', iso: 'PK' }],
  93: [{ name: 'Afeganistão', iso: 'AF' }],
  94: [{ name: 'Sri Lanka', iso: 'LK' }],
  95: [{ name: 'Mianmar', iso: 'MM' }],
  98: [{ name: 'Irã', iso: 'IR' }],
  212: [
    { name: 'Marrocos', iso: 'MA' },
    { name: 'Saara Ocidental', iso: 'EH' },
  ],
  213: [{ name: 'Argélia', iso: 'DZ' }],
  216: [{ name: 'Tunísia', iso: 'TN' }],
  218: [{ name: 'Líbia', iso: 'LY' }],
  220: [{ name: 'Gâmbia', iso: 'GM' }],
  221: [{ name: 'Senegal', iso: 'SN' }],
  222: [{ name: 'Mauritânia', iso: 'MR' }],
  223: [{ name: 'Mali', iso: 'ML' }],
  224: [{ name: 'Guiné', iso: 'GN' }],
  225: [{ name: 'Costa do Marfim', iso: 'CI' }],
  226: [{ name: 'Burkina Faso', iso: 'BF' }],
  227: [{ name: 'Níger', iso: 'NE' }],
  228: [{ name: 'Togo', iso: 'TG' }],
  229: [{ name: 'Benin', iso: 'BJ' }],
  230: [{ name: 'Maurício', iso: 'MU' }],
  231: [{ name: 'Libéria', iso: 'LR' }],
  232: [{ name: 'Serra Leoa', iso: 'SL' }],
  233: [{ name: 'Gana', iso: 'GH' }],
  234: [{ name: 'Nigéria', iso: 'NG' }],
  235: [{ name: 'Chade', iso: 'TD' }],
  236: [{ name: 'República Centro-Africana', iso: 'CF' }],
  237: [{ name: 'Camarões', iso: 'CM' }],
  238: [{ name: 'Cabo Verde', iso: 'CV' }],
  239: [{ name: 'São Tomé e Príncipe', iso: 'ST' }],
  240: [{ name: 'Guiné Equatorial', iso: 'GQ' }],
  241: [{ name: 'Gabão', iso: 'GA' }],
  242: [{ name: 'República do Congo', iso: 'CG' }],
  243: [{ name: 'República Democrática do Congo', iso: 'CD' }],
  244: [{ name: 'Angola', iso: 'AO' }],
  245: [{ name: 'Guiné-Bissau', iso: 'GW' }],
  246: [{ name: 'Território Britânico do Oceano Índico', iso: 'IO' }],
  247: [{ name: 'Ilha Ascensão', iso: 'AC' }],
  248: [{ name: 'Seicheles', iso: 'SC' }],
  249: [{ name: 'Sudão', iso: 'SD' }],
  250: [{ name: 'Ruanda', iso: 'RW' }],
  251: [{ name: 'Etiópia', iso: 'ET' }],
  252: [{ name: 'Somália', iso: 'SO' }],
  253: [{ name: 'Djibuti', iso: 'DJ' }],
  254: [{ name: 'Quênia', iso: 'KE' }],
  255: [{ name: 'Tanzânia', iso: 'TZ' }],
  256: [{ name: 'Uganda', iso: 'UG' }],
  257: [{ name: 'Burundi', iso: 'BI' }],
  258: [{ name: 'Moçambique', iso: 'MZ' }],
  260: [{ name: 'Zâmbia', iso: 'ZM' }],
  261: [{ name: 'Madagáscar', iso: 'MG' }],
  262: [
    { name: 'Reunião', iso: 'RE' },
    { name: 'Mayotte', iso: 'YT' },
  ],
  263: [{ name: 'Zimbábue', iso: 'ZW' }],
  264: [{ name: 'Namíbia', iso: 'NA' }],
  265: [{ name: 'Malaui', iso: 'MW' }],
  266: [{ name: 'Lesoto', iso: 'LS' }],
  267: [{ name: 'Botsuana', iso: 'BW' }],
  268: [{ name: 'Essuatíni', iso: 'SZ' }],
  269: [{ name: 'Comores', iso: 'KM' }],
  290: [{ name: 'Santa Helena', iso: 'SH' }],
  291: [{ name: 'Eritreia', iso: 'ER' }],
  297: [{ name: 'Aruba', iso: 'AW' }],
  298: [{ name: 'Ilhas Faroe', iso: 'FO' }],
  299: [{ name: 'Groenlândia', iso: 'GL' }],
  350: [{ name: 'Gibraltar', iso: 'GI' }],
  351: [{ name: 'Portugal', iso: 'PT' }],
  352: [{ name: 'Luxemburgo', iso: 'LU' }],
  353: [{ name: 'Irlanda', iso: 'IE' }],
  354: [{ name: 'Islândia', iso: 'IS' }],
  355: [{ name: 'Albânia', iso: 'AL' }],
  356: [{ name: 'Malta', iso: 'MT' }],
  357: [{ name: 'Chipre', iso: 'CY' }],
  358: [{ name: 'Finlândia', iso: 'FI' }],
  359: [{ name: 'Bulgária', iso: 'BG' }],
  370: [{ name: 'Lituânia', iso: 'LT' }],
  371: [{ name: 'Letônia', iso: 'LV' }],
  372: [{ name: 'Estônia', iso: 'EE' }],
  373: [{ name: 'Moldávia', iso: 'MD' }],
  374: [{ name: 'Armênia', iso: 'AM' }],
  375: [{ name: 'Bielorrússia', iso: 'BY' }],
  376: [{ name: 'Andorra', iso: 'AD' }],
  377: [{ name: 'Mônaco', iso: 'MC' }],
  378: [{ name: 'San Marino', iso: 'SM' }],
  380: [{ name: 'Ucrânia', iso: 'UA' }],
  381: [{ name: 'Sérvia', iso: 'RS' }],
  382: [{ name: 'Montenegro', iso: 'ME' }],
  383: [{ name: 'Kosovo', iso: 'XK' }],
  385: [{ name: 'Croácia', iso: 'HR' }],
  386: [{ name: 'Eslovênia', iso: 'SI' }],
  387: [{ name: 'Bósnia e Herzegovina', iso: 'BA' }],
  389: [{ name: 'Macedônia do Norte', iso: 'MK' }],
  420: [{ name: 'República Tcheca', iso: 'CZ' }],
  421: [{ name: 'Eslováquia', iso: 'SK' }],
  423: [{ name: 'Liechtenstein', iso: 'LI' }],
  500: [{ name: 'Ilhas Falkland', iso: 'FK' }],
  501: [{ name: 'Belize', iso: 'BZ' }],
  502: [{ name: 'Guatemala', iso: 'GT' }],
  503: [{ name: 'El Salvador', iso: 'SV' }],
  504: [{ name: 'Honduras', iso: 'HN' }],
  505: [{ name: 'Nicarágua', iso: 'NI' }],
  506: [{ name: 'Costa Rica', iso: 'CR' }],
  507: [{ name: 'Panamá', iso: 'PA' }],
  508: [{ name: 'Saint-Pierre e Miquelon', iso: 'PM' }],
  509: [{ name: 'Haiti', iso: 'HT' }],
  590: [
    { name: 'Guadalupe', iso: 'GP' },
    { name: 'São Bartolomeu', iso: 'BL' },
    { name: 'São Martinho (parte francesa)', iso: 'MF' },
  ],
  591: [{ name: 'Bolívia', iso: 'BO' }],
  592: [{ name: 'Guiana', iso: 'GY' }],
  593: [{ name: 'Equador', iso: 'EC' }],
  594: [{ name: 'Guiana Francesa', iso: 'GF' }],
  595: [{ name: 'Paraguai', iso: 'PY' }],
  596: [{ name: 'Martinica', iso: 'MQ' }],
  597: [{ name: 'Suriname', iso: 'SR' }],
  598: [{ name: 'Uruguai', iso: 'UY' }],
  599: [
    { name: 'Curaçao', iso: 'CW' },
    { name: 'Bonaire', iso: 'BQ' },
  ],
  670: [{ name: 'Timor-Leste', iso: 'TL' }],
  672: [{ name: 'Ilha Norfolk', iso: 'NF' }],
  673: [{ name: 'Brunei', iso: 'BN' }],
  674: [{ name: 'Nauru', iso: 'NR' }],
  675: [{ name: 'Papua Nova Guiné', iso: 'PG' }],
  676: [{ name: 'Tonga', iso: 'TO' }],
  677: [{ name: 'Ilhas Salomão', iso: 'SB' }],
  678: [{ name: 'Vanuatu', iso: 'VU' }],
  679: [{ name: 'Fiji', iso: 'FJ' }],
  680: [{ name: 'Palau', iso: 'PW' }],
  681: [{ name: 'Wallis e Futuna', iso: 'WF' }],
  682: [{ name: 'Ilhas Cook', iso: 'CK' }],
  683: [{ name: 'Niue', iso: 'NU' }],
  685: [{ name: 'Samoa', iso: 'WS' }],
  686: [{ name: 'Kiribati', iso: 'KI' }],
  687: [{ name: 'Nova Caledônia', iso: 'NC' }],
  688: [{ name: 'Tuvalu', iso: 'TV' }],
  689: [{ name: 'Polinésia Francesa', iso: 'PF' }],
  690: [{ name: 'Tokelau', iso: 'TK' }],
  691: [{ name: 'Micronésia', iso: 'FM' }],
  692: [{ name: 'Ilhas Marshall', iso: 'MH' }],
  850: [{ name: 'Coreia do Norte', iso: 'KP' }],
  852: [{ name: 'Hong Kong', iso: 'HK' }],
  853: [{ name: 'Macau', iso: 'MO' }],
  855: [{ name: 'Camboja', iso: 'KH' }],
  856: [{ name: 'Laos', iso: 'LA' }],
  880: [{ name: 'Bangladesh', iso: 'BD' }],
  886: [{ name: 'Taiwan', iso: 'TW' }],
  960: [{ name: 'Maldivas', iso: 'MV' }],
  961: [{ name: 'Líbano', iso: 'LB' }],
  962: [{ name: 'Jordânia', iso: 'JO' }],
  963: [{ name: 'Síria', iso: 'SY' }],
  964: [{ name: 'Iraque', iso: 'IQ' }],
  965: [{ name: 'Kuwait', iso: 'KW' }],
  966: [{ name: 'Arábia Saudita', iso: 'SA' }],
  967: [{ name: 'Iêmen', iso: 'YE' }],
  968: [{ name: 'Omã', iso: 'OM' }],
  970: [{ name: 'Palestina', iso: 'PS' }],
  971: [{ name: 'Emirados Árabes Unidos', iso: 'AE' }],
  972: [{ name: 'Israel', iso: 'IL' }],
  973: [{ name: 'Bahrein', iso: 'BH' }],
  974: [{ name: 'Catar', iso: 'QA' }],
  975: [{ name: 'Butão', iso: 'BT' }],
  976: [{ name: 'Mongólia', iso: 'MN' }],
  977: [{ name: 'Nepal', iso: 'NP' }],
  992: [{ name: 'Tadjiquistão', iso: 'TJ' }],
  993: [{ name: 'Turcomenistão', iso: 'TM' }],
  994: [{ name: 'Azerbaijão', iso: 'AZ' }],
  995: [{ name: 'Geórgia', iso: 'GE' }],
  996: [{ name: 'Quirguistão', iso: 'KG' }],
  998: [{ name: 'Uzbequistão', iso: 'UZ' }],
}

/** Retorna os países associados a um DDI, ou undefined se não encontrado */
export function lookupDdi(ddi: number): DdiCountry[] | undefined {
  return DDI_MAP[ddi]
}
