import { grayscaleCommand } from './media/grayscale.command.js'
import { gayFlagCommand } from './media/gayflag.command.js'
import { craqueCommand } from './media/craque.command.js'
import { dddCommand } from './utility/ddd.command.js'
import { ddiCommand } from './utility/ddi.command.js'
import { bootCorrectionCommand } from './fun/boot-correction.command.js'
import { coinCommand } from './fun/coin.command.js'
import { diceCommand } from './fun/dice.command.js'
import { emojiCommand } from './fun/emoji.command.js'
import { mathCommand } from './fun/math.command.js'
import { reactCommand } from './fun/react.command.js'
import { disableGroupConfigCommand, enableGroupConfigCommand, setGroupConfigCommand, showGroupConfigCommand } from './groups/group-config.command.js'
import { addParticipantCommand, banCommand, callAdminsCommand, closeGroupCommand, deleteGroupMessageCommand, demoteCommand, everyoneCommand, giveawayAdminsCommand, giveawayCommand, membershipRequestsCommand, openGroupCommand, promoteCommand, rulesCommand, russianRouletteCommand } from './groups/group-moderation.command.js'
import { bgCommand } from './stickers/bg.command.js'
import { attpCommand } from './stickers/attp.command.js'
import { createStickerCommand } from './stickers/create-sticker.command.js'
import { cropStickerCommand } from './stickers/crop.command.js'
import { fitStickerCommand } from './stickers/fit.command.js'
import { stealStickerCommand } from './stickers/steal-sticker.command.js'
import { stickerToMediaCommand } from './stickers/sticker-to-media.command.js'
import { stretchStickerCommand } from './stickers/stretch.command.js'
import { searchStickerLyCommand } from './stickers/sticker-ly-search.command.js'
import { packStickerLyCommand } from './stickers/sticker-ly-pack.command.js'
import { trendingStickerLyCommand } from './stickers/sticker-ly-trending.command.js'
import { ttpCommand } from './stickers/ttp.command.js'
import { menuCommand } from './system/menu.command.js'
import { pingCommand } from './system/ping.command.js'
import { statusCommand } from './system/status.command.js'
import { timeCommand } from './system/time.command.js'
import { randomVerseCommand } from './bible/random-verse.command.js'
import { randomChapterCommand } from './bible/random-chapter.command.js'
import { getChapterCommand } from './bible/get-chapter.command.js'
import { getVerseCommand } from './bible/get-verse.command.js'
import { searchBibleCommand, searchBibleAllCommand } from './bible/search-bible.command.js'
import { implicitVerseCommand } from './bible/implicit-verse.command.js'

export const commands = [menuCommand, grayscaleCommand, gayFlagCommand, craqueCommand, pingCommand, statusCommand, timeCommand, showGroupConfigCommand, enableGroupConfigCommand, disableGroupConfigCommand, setGroupConfigCommand, openGroupCommand, closeGroupCommand, promoteCommand, demoteCommand, banCommand, addParticipantCommand, deleteGroupMessageCommand, callAdminsCommand, everyoneCommand, giveawayCommand, giveawayAdminsCommand, russianRouletteCommand, rulesCommand, membershipRequestsCommand, createStickerCommand, fitStickerCommand, cropStickerCommand, stretchStickerCommand, stealStickerCommand, bgCommand, stickerToMediaCommand, searchStickerLyCommand, packStickerLyCommand, trendingStickerLyCommand, attpCommand, implicitVerseCommand, ttpCommand, emojiCommand, reactCommand, bootCorrectionCommand, coinCommand, diceCommand, mathCommand, dddCommand, ddiCommand, getVerseCommand, getChapterCommand, randomVerseCommand, randomChapterCommand, searchBibleCommand, searchBibleAllCommand]

export { grayscaleCommand, gayFlagCommand, craqueCommand, addParticipantCommand, attpCommand, banCommand, bgCommand, bootCorrectionCommand, callAdminsCommand, closeGroupCommand, coinCommand, createStickerCommand, cropStickerCommand, dddCommand, demoteCommand, ddiCommand, diceCommand, deleteGroupMessageCommand, disableGroupConfigCommand, emojiCommand, enableGroupConfigCommand, everyoneCommand, fitStickerCommand, giveawayAdminsCommand, giveawayCommand, mathCommand, membershipRequestsCommand, menuCommand, openGroupCommand, promoteCommand, reactCommand, pingCommand, rulesCommand, russianRouletteCommand, setGroupConfigCommand, showGroupConfigCommand, statusCommand, stealStickerCommand, stickerToMediaCommand, stretchStickerCommand, searchStickerLyCommand, packStickerLyCommand, trendingStickerLyCommand, timeCommand, ttpCommand, randomVerseCommand, randomChapterCommand, getChapterCommand, getVerseCommand, searchBibleCommand, searchBibleAllCommand, implicitVerseCommand }
